// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pxf/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protowire.Pxf {

  /// <summary>Holder for reflection information generated from pxf/annotations.proto</summary>
  public static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for pxf/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVweGYvYW5ub3RhdGlvbnMucHJvdG8SA3B4ZhogZ29vZ2xlL3Byb3RvYnVm",
            "L2Rlc2NyaXB0b3IucHJvdG86OgoIcmVxdWlyZWQSHS5nb29nbGUucHJvdG9i",
            "dWYuRmllbGRPcHRpb25zGKIKIAEoCFIIcmVxdWlyZWQ6OAoHZGVmYXVsdBId",
            "Lmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYowogASgJUgdkZWZhdWx0",
            "QlEKB2NvbS5weGZCEEFubm90YXRpb25zUHJvdG9QAaICA1BYWKoCDVByb3Rv",
            "d2lyZS5QeGbKAgNQeGbiAg9QeGZcR1BCTWV0YWRhdGHqAgNQeGZiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { AnnotationsExtensions.Required, AnnotationsExtensions.Default }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of pxf/annotations.proto</summary>
  public static partial class AnnotationsExtensions {
    /// <summary>
    /// Mark a field as required in PXF. Absent fields cause a validation error.
    /// A field set to null still counts as present.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> Required =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(1314, pb::FieldCodec.ForBool(10512, false));
    /// <summary>
    /// Default value applied when a field is absent (not null) in PXF.
    /// The value is a PXF literal string, e.g. "42", "true", "\"hello\"".
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Default =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(1315, pb::FieldCodec.ForString(10522, ""));
  }

}

#endregion Designer generated code
